# Generated by Django 4.2.7 on 2024-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyhotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='bookmyhotel/hotel_images'),
        ),
        migrations.AlterField(
            model_name='hotelroomimage',
            name='image',
            field=models.ImageField(upload_to='bookmyhotel/hotel_room_images'),
        ),
    ]
